// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxHucfMPu_eX8Y3vs3lQcUrAyquKZvGxc',
    appId: '1:1096335379004:web:911bd8401d986583825139',
    messagingSenderId: '1096335379004',
    projectId: 'photography-app-2fa2f',
    authDomain: 'photography-app-2fa2f.firebaseapp.com',
    storageBucket: 'photography-app-2fa2f.appspot.com',
    measurementId: 'G-GF5JT8GKLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiO57G2ezrvjzC7o4cxpcB2su3MelSzVs',
    appId: '1:1096335379004:android:76b70874cc83750b825139',
    messagingSenderId: '1096335379004',
    projectId: 'photography-app-2fa2f',
    storageBucket: 'photography-app-2fa2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwx2bitZAYa4MC6yoNBUfqDZ8aWmI698',
    appId: '1:1096335379004:ios:adf93ccef826aebd825139',
    messagingSenderId: '1096335379004',
    projectId: 'photography-app-2fa2f',
    storageBucket: 'photography-app-2fa2f.appspot.com',
    androidClientId: '1096335379004-o6vfd3ilf2e391un3hjv9tu841lkaapa.apps.googleusercontent.com',
    iosClientId: '1096335379004-mrt50omaov56gh5hvvdqvq79j6p4q9tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.photographyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJwx2bitZAYa4MC6yoNBUfqDZ8aWmI698',
    appId: '1:1096335379004:ios:adf93ccef826aebd825139',
    messagingSenderId: '1096335379004',
    projectId: 'photography-app-2fa2f',
    storageBucket: 'photography-app-2fa2f.appspot.com',
    androidClientId: '1096335379004-o6vfd3ilf2e391un3hjv9tu841lkaapa.apps.googleusercontent.com',
    iosClientId: '1096335379004-mrt50omaov56gh5hvvdqvq79j6p4q9tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.photographyApp',
  );
}
